- name: Create /opt/git directory
  ansible.builtin.file:
    path: /opt/git
    state: directory
    mode: "0755"
    owner: oklab
    group: oklab
  tags: application_setup

- name: Clone open-uranus-api repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-uranus-api.git
    dest: /opt/git/open-uranus-api
  become_user: oklab
  tags: application_setup

- name: Create .env file for open-uranus-api
  ansible.builtin.template:
    src: dotenv.j2
    dest: /opt/git/open-uranus-api/.env
    owner: oklab
    group: oklab
    mode: "0644"
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-uranus-api
  ansible.builtin.pip:
    requirements: /opt/git/open-uranus-api/requirements.txt
    virtualenv: /opt/git/open-uranus-api/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Copy open-uranus-api.service file
  ansible.builtin.copy:
    src: services/open-uranus-api.service
    dest: /etc/systemd/system/open-uranus-api.service
    owner: root
    group: root
    mode: "0644"
  tags: application_setup

- name: Enable and start open-uranus-api service
  ansible.builtin.systemd:
    name: open-uranus-api.service
    enabled: true
    state: started
  tags: application_setup

- name: Clone open-uranus-admin repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-uranus-admin.git
    dest: /opt/git/open-uranus-admin
  become_user: oklab
  tags: application_setup

- name: Create .env file for open-uranus-admin
  ansible.builtin.template:
    src: dotenv_uranus_admin.j2
    dest: /opt/git/open-uranus-admin/.env
    owner: oklab
    group: oklab
    mode: "0644"
  become_user: oklab
  tags: application_setup

- name: Run pnpm install for open-uranus-admin
  ansible.builtin.command:
    cmd: pnpm install
    chdir: /opt/git/open-uranus-admin
  become_user: oklab
  tags: application_setup

- name: Run pnpm build for open-uranus-admin
  ansible.builtin.command:
    cmd: pnpm build
    chdir: /opt/git/open-uranus-admin
  become_user: oklab
  tags: application_setup

- name: Copy open-uranus-admin.service file
  ansible.builtin.copy:
    src: services/open-uranus-admin.service
    dest: /etc/systemd/system/open-uranus-admin.service
    owner: root
    group: root
    mode: "0644"
  tags: application_setup

- name: Enable and start open-uranus-admin service
  ansible.builtin.systemd:
    name: open-uranus-admin.service
    enabled: true
    state: started
  tags: application_setup

- name: Clone open-school-map repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-school-map.git
    dest: /opt/git/open-school-map
  become_user: oklab
  tags: application_setup

- name: Create .env file for open-school-map
  ansible.builtin.template:
    src: dotenv.j2
    dest: /opt/git/open-school-map/.env
    owner: oklab
    group: oklab
    mode: "0644"
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-data-api
  ansible.builtin.pip:
    requirements: /opt/git/open-data-api/requirements.txt
    virtualenv: /opt/git/open-data-api/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Run pnpm install for open-school-map
  ansible.builtin.command:
    cmd: pnpm install
    chdir: /opt/git/open-school-map
  become_user: oklab
  tags: application_setup

- name: Run pnpm build for open-school-map
  ansible.builtin.command:
    cmd: pnpm build
    chdir: /opt/git/open-school-map
  become_user: oklab
  tags: application_setup

- name: Clone open-data-api repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-data-api.git
    dest: /opt/git/open-data-api
  become_user: oklab
  tags: application_setup

- name: Create .env file for open-data-api
  ansible.builtin.template:
    src: dotenv.j2
    dest: /opt/git/open-data-api/.env
    owner: oklab
    group: oklab
    mode: "0644"
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-data-api
  ansible.builtin.pip:
    requirements: /opt/git/open-data-api/requirements.txt
    virtualenv: /opt/git/open-data-api/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-data-api tools
  ansible.builtin.pip:
    requirements: /opt/git/open-data-api/tools/requirements.txt
    virtualenv: /opt/git/open-data-api/tools/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Copy open-data-api.service file
  ansible.builtin.copy:
    src: services/open-data-api.service
    dest: /etc/systemd/system/open-data-api.service
    owner: root
    group: root
    mode: "0644"
  tags: application_setup

- name: Enable and start open-data-api service
  ansible.builtin.systemd:
    name: open-data-api.service
    enabled: true
    state: started
  tags: application_setup

- name: Clone open-social-map repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-social-map.git
    dest: /opt/git/open-social-map
  become_user: oklab
  tags: application_setup

- name: Create .env file for open-social-map
  ansible.builtin.template:
    src: dotenv.j2
    dest: /opt/git/open-social-map/.env
    owner: oklab
    group: oklab
    mode: "0644"
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-social-map tools
  ansible.builtin.pip:
    requirements: /opt/git/open-social-map/tools/requirements.txt
    virtualenv: /opt/git/open-social-map/tools/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Clone open-monuments-map repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-monuments-map.git
    dest: /opt/git/open-monuments-map
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-monuments-map tools
  ansible.builtin.pip:
    requirements: /opt/git/open-monuments-map/tools/requirements.txt
    virtualenv: /opt/git/open-monuments-map/tools/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Run pnpm install for open-monuments-map
  ansible.builtin.command:
    cmd: pnpm install
    chdir: /opt/git/open-monuments-map
  become_user: oklab
  tags: application_setup

- name: Run pnpm build for open-monuments-map
  ansible.builtin.command:
    cmd: pnpm build
    chdir: /opt/git/open-monuments-map
  become_user: oklab
  tags: application_setup

- name: Clone open-accident-map repository
  ansible.builtin.git:
    repo: https://github.com/oklabflensburg/open-accident-map.git
    dest: /opt/git/open-accident-map
  become_user: oklab
  tags: application_setup

- name: Create virtual environment for open-accident-map tools
  ansible.builtin.pip:
    requirements: /opt/git/open-accident-map/tools/requirements.txt
    virtualenv: /opt/git/open-accident-map/tools/venv
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
  become_user: oklab
  tags: application_setup

- name: Run SQL scripts to create schemas
  community.postgresql.postgresql_script:
    db: "{{ db_name }}"
    port: "{{ db_port }}"
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    path: "{{ item }}"
  with_items:
    - /opt/git/open-social-map/data/flensburg_sozialatlas.sql
    - /opt/git/open-social-map/data/flensburg_sozialatlas_meta.sql
    - /opt/git/open-monuments-map/data/denkmalliste_schema.sql
    - /opt/git/open-data-api/data/de_biomass_units_schema.sql
    - /opt/git/open-data-api/data/de_combustion_units_schema.sql
    - /opt/git/open-data-api/data/de_district_numbers_schema.sql
    - /opt/git/open-data-api/data/de_energy_meta_schema.sql
    - /opt/git/open-data-api/data/de_municipality_numbers_schema.sql
    - /opt/git/open-data-api/data/de_nuclear_units_schema.sql
    - /opt/git/open-data-api/data/de_solar_units_schema.sql
    - /opt/git/open-data-api/data/de_water_units_schema.sql
    - /opt/git/open-data-api/data/de_weather_stations_schema.sql
    - /opt/git/open-data-api/data/de_wind_units_schema.sql
    - /opt/git/open-data-api/data/dwd_abbreviations_schema.sql
    - /opt/git/open-data-api/data/dwd_station_reference_schema.sql
    - /opt/git/open-data-api/data/eu_country_codes_schema.sql
    - /opt/git/open-data-api/data/global_mosmix_stations_schema.sql
    - /opt/git/open-data-api/data/sh_archaeological_monument_schema.sql
    - /opt/git/open-school-map/data/sh_school_schema.sql
  become_user: oklab
  tags: application_setup
