---
- hosts: all
  remote_user: "{{ ansible_user }}"

  vars_files:
    - vars.yml

  tasks:
    - name: Add monoment geometries to database
      ansible.builtin.shell:
        cmd: |
          "python {{ item }}"
        chdir: /opt/git/open-monuments-map
        executable: /opt/git/open-monuments-map/venv/bin/python
      with_items:
        - "insert_boundaries.py /opt/git/open-monuments-map/data/monument_boundaries.geojson"
        - "insert_monuments.py /opt/git/open-monuments-map/data/stadt-flensburg-denkmalschutz.geojson"

    - name: Add districts geometries to database
      ansible.builtin.shell:
        cmd: |
          "python {{ item }}"
        chdir: /opt/git/open-social-map
        executable: /opt/git/open-social-map/venv/bin/python
      with_items:
        - "insert_geography.py /opt/git/open-social-map/data/flensburg_stadtteile.geojson"
