---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Initial System Setup
      include_tasks: tasks/initial_setup.yml
      tags: initial_setup

  tasks:
    - include_tasks: tasks/postgresql_setup.yml

    - include_tasks: tasks/nginx_setup.yml
      tags: nginx_setup

    - include_tasks: tasks/vg25_import.yml

    - include_tasks: tasks/open-school-map.yml
      tags: open-school-map

    - include_tasks: tasks/open-social-map.yml
      tags: open-social-map

    - include_tasks: tasks/open-accident-map.yml
      tags: open-accident-map

    - include_tasks: tasks/open-data-api.yml
      tags: open-data-api

    - include_tasks: tasks/open-monuments-map.yml
      tags: open-monuments-map

    - include_tasks: tasks/open-uranus-admin.yml
      tags: open-uranus-admin

    - include_tasks: tasks/open-uranus-api.yml
      tags: open-uranus-api

    - include_tasks: tasks/open-biotope-map.yml
      tags: open-biotope-map

    - include_tasks: tasks/open-parcel-map.yml
      tags: open-parcel-map

    - include_tasks: tasks/open-recycling-map.yml
      tags: open-recycling-map

    - include_tasks: tasks/open-surface-map.yml
      tags: open-surface-map

    - include_tasks: tasks/open-playgrounds-map.yml
      tags: open-playgrounds-map

    - include_tasks: tasks/open-trees-map.yml
      tags: open-trees-map

    - include_tasks: tasks/create_indexes.yml


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart postgres
      service:
        name: postgresql
        state: restarted