---
- hosts: all
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - include_tasks: tasks/initial_setup.yml
      tags: initial_setup

  tasks:
    - include_tasks: tasks/postgresql_setup.yml
      tags: postgresql_setup

    - include_tasks: tasks/nginx_setup.yml
      tags: nginx_setup

    - include_tasks: tasks/application_setup.yml
      tags: application_setup

    - include_tasks: tasks/vg25_import.yml
      tags: vg25_import

    - include_tasks: tasks/create_indexes.yml
      tags: create_indexes

    - include_tasks: tasks/data_import.yml
      tags: data_import

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted