---
- hosts: all
  remote_user: "{{ ansible_user }}"

  vars_files:
    - vars.yml

  tasks:
    - name: Clone listed project repositories
      ansible.builtin.git:
        repo: "https://github.com/oklabflensburg/{{ item }}.git"
        dest: "/opt/git/{{ item }}"
      with_items:
        - open-accident-map
        - open-local-elections-map
        - open-monuments-map
        - open-playgrounds-map
        - open-recycling-map
        - open-sensor-map
        - open-social-map
        - open-surface-map

    - name: Copy enviroment files to repo from template
      template: 
        src: env.j2 
        dest: "/opt/git/{{ item }}/.env"
      with_items:
        - open-accident-map
        - open-local-elections-map
        - open-monuments-map
        - open-playgrounds-map
        - open-recycling-map
        - open-sensor-map
        - open-social-map
        - open-surface-map

    - name: Set python virualenv
      command:
        cmd: "virtualenv /opt/git/{{ item }}/venv -p python3"
        creates: "/opt/git/{{ item }}/venv"
      with_items:
        - open-accident-map
        - open-local-elections-map
        - open-monuments-map
        - open-recycling-map
        - open-sensor-map
        - open-social-map

    - name: Install python requirements
      ansible.builtin.pip:
        requirements: "/opt/git/{{ item }}/requirements.txt"
        virtualenv: "/opt/git/{{ item }}/venv"
        virtualenv_python: python3
      with_items:
        - open-accident-map
        - open-local-elections-map
        - open-monuments-map
        - open-recycling-map
        - open-sensor-map
        - open-social-map
