name: API Schemathesis tests

on:
  push:
    paths:
     - 'app/**/*.py'
  pull_request:
    paths:
     - 'app/**/*.py'

jobs:
  api-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: schemathesis/action@v1
        with:
          schema: 'https://api.oklabflensburg.de/openapi.json --experimental=openapi-3.1'
